[build]
  command = "CI=false npm install && npm run build --workspace=client" # <-- Add CI=false
  publish = "client/build"
  environment = { CI = "false" }

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/api/:splat"  # Or your backend's production URL
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200